version: "3.9"

networks:
  # Only the proxy will be exposed to the outside network. All services that
  # need to be accessible outside of the network need to be in this network.
  proxied:

services:
  proxy:
    container_name: stats.proxy.production
    restart: always
    image: nginx:1.23.3-alpine
    ports:
      - 8009:80
    volumes:
      - ./proxy/production.conf:/etc/nginx/nginx.conf
      - ./proxy/logs:/var/log/nginx

    # Make sure that all services that need to be proxied are running before we
    # start proxying.
    depends_on:
      - web
    networks:
      - proxied

  api:
    container_name: stats.api.production
    restart: always
    build:
      context: ./api/
      dockerfile: production.dockerfile
    expose:
      - "80"
    environment:
      SUPERUSER_NAME: ${SUPERUSER_NAME}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
      DATABASE_NAME: "stats.db"
      UPDATE_INTERVAL: "60000"
    volumes:
     - ./collector/data:/data:rw
    networks:
      - proxied

  web:
    container_name: stats.web.production
    restart: always
    build:
      context: ./web/
      dockerfile: production.dockerfile
    expose:
      - "80"
    networks:
      - proxied

  collector:
    container_name: stats.collector.production
    restart: always
    build:
      context: ./collector/
    environment:
      DATABASE_NAME: "stats.db"
      LOGFILE_NAME: "access.log"
      UPDATE_INTERVAL: "60000"
    volumes:
     - ./collector/data:/data:rw
     - ./proxy/logs:/logs:ro
