version: "3.8"

networks:
  protected:

  # Only the proxy will be exposed to the outside network. All services that
  # need to be accessible outside of the network need to be in this network.
  proxied:

services:
  proxy:
    container_name: stats.proxy.production
    restart: always
    image: nginx:1.23.3-alpine
    ports:
      - 8009:80
    volumes:
      - ./proxy/production.conf:/etc/nginx/nginx.conf
      - ./proxy/logs:/var/log/nginx

    # Make sure that all services that need to be proxied are running before we
    # start proxying.
    depends_on:
      - client
    networks:
      - proxied

  client:
    container_name: stats.client.production
    restart: always
    build:
      context: ./client/
    expose:
      - "80"
    networks:
      - proxied

  collector:
    container_name: stats.collector.production
    restart: always
    build:
      context: ./collector/
    volumes:
     - ./collector/data:/data:rw
     - ./proxy/logs:/logs:ro
    networks:
      - protected